### ISSUE TITLE
Add ability to pass parameters file through the command line

### ISSUE THREAD

**Issue by pcm32** [seliv55/isodyn#2]
Currently, isodyn is reading from the compilation directory a file named "1" which holds parameters. This is difficult to replicate in the container usage scenario and hence we need to be able to pass an equivalent file with parameters through the command line.

**Comment by seliv55** [comment]
Now Isodyn accepts input file as a parameter. Since input files have the same structure as the produced output files with changed parameters, which also can be used as input, the input and output files are situated in the same directory. Now the directory is "./out". The command to run Isodyn with the experimental data in file "midcorout.csv" and parameter file "1" is:
./isodyn.out  midcorout.csv  out/1

**Comment by pcm32** [comment]
Thanks Vitaly!
